format_version: 10
pipelines:
  deploy:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ffe832e:
        git: https://github.com/benoitmellier/testcd.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy-app:
            elastic_profile_id: demo-app
            timeout: 0
            tasks:
            - exec:
                arguments:
                command: ./deploy.sh
                run_if: passed